# Generated by Django 5.0.14 on 2025-11-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AyurX', '0002_hospital_receptionist_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
